Alkofahi terraform setup script
retaildevcrews/caf-terraform-landingzones-starter pull request #2
Opened 2021-03-30 15:41 UTC by alkofahi

# [611](https://github.com/Azure/caf-terraform-landingzones-starter/issues/611) & [612](https://github.com/Azure/caf-terraform-landingzones-starter/issues/612)

## PR Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My code follows the code style of this project.
- [ ] I ran lint checks locally prior to submission.
- [ ] Have you checked to ensure there aren't other open Pull Requests for the same update/change?

## Description

Adding shell script to automate the creation of the service principal and remote state resources, this script can be used to provision an environment using Terraform

These scripts are based on the ones discussed here https://github.com/retaildevcrews/ServicePrincipal/tree/main/infra
    
This is related to tasks #612 and #611

## Does this introduce a breaking change

- [ ] YES
- [ ] NO

## Testing

Ran the script successfully from my local machine. It created resource group *rg-jafartest4-cse-dev-tf* to hold the Terraform's remote state. It also successfully created the *jafartest4-sp-dev*  service principal (no roles assigned at the moment)

2021-03-30 15:47 UTC, gortegaMS requested changes
Do we need general instructions about how to run these scripts ?

2021-03-30 16:01 UTC, alkofahi commented
> Do we need general instructions about how to run these scripts ?

I was thinking of adding the documentation after integration. Let me add a short guide on how to use the script as part of this PR and we can expand upon it later.

2021-03-30 18:11 UTC, Natasha-Kohli approved these changes

2021-03-30 20:01 UTC, Natasha-Kohli commented on provision_environment/_prepare-terraform.sh
> +    echo -e "${green}\tterraform.tfvars created${reset}"
typo: should this be "${green}\terraform.tfvars..."

2021-03-30 20:28 UTC, Natasha-Kohli commented
I ran the script myself and ran into an issue with TF_CLIENT_SECRET, when the terraform.tfvars file is created that variable has "<<svc_ppl_CLIENT_SECRET>>" in the middle of the secret string

2021-03-30 21:30 UTC, alkofahi commented on provision_environment/_prepare-terraform.sh
> +    echo -e "${green}\tterraform.tfvars created${reset}"
Nice catch, thanks!

2021-03-31 02:23 UTC, alkofahi commented on provision_environment/_prepare-terraform.sh
> +    echo -e "${green}\tterraform.tfvars created${reset}"
Ok today has been a long day, this is correct its a \t for tab white space combined with terraform..so this is correct

2021-03-31 02:25 UTC, alkofahi commented
> I ran the script myself and ran into an issue with TF_CLIENT_SECRET, when the terraform.tfvars file is created that variable has "<<svc_ppl_CLIENT_SECRET>>" in the middle of the secret string

Did the run succeed for you? I tried it a couple of times and everything worked as expected

2021-03-31 14:20 UTC, gortegaMS approved these changes
Please create a new issue to capture the following comments:

- I noticed that this script uses a naming convention when creating resources eg. **rg-** is used to prefix a resource group. We need to make sure that naming convention  aligns with PnP.  
- it would be a good idea if do indicate what is the starting directory before to try run the script e.g. **cd provision_environment/**
- also indicating that you need to login into azure and set your desire subscription . e.g. **az login** and **az account set --subscription [subscription]**

- Ran into an error and I had to manually delete the resources and try a different name, I believe the SP project had and other script to do second round .

![image](https://user-images.githubusercontent.com/70150605/113157269-5e056800-9200-11eb-8561-a2f13c0dc904.png)

2021-03-31 14:20 UTC, gortegaMS commented on provision_environment/README.md
> +
Please create a new issue to capture the following comments:

- I noticed that this script uses a naming convention when creating resources eg. **rg-** is used to prefix a resource group. We need to make sure that naming convention  aligns with PnP.  
- it would be a good idea if do indicate what is the starting directory before to try run the script e.g. **cd provision_environment/**
- also indicating that you need to login into azure and set your desire subscription . e.g. **az login** and **az account set --subscription [subscription]**

- Ran into an error and I had to manually delete the resources and try a different name, I believe the SP project had and other script to do second round .

![image](https://user-images.githubusercontent.com/70150605/113157269-5e056800-9200-11eb-8561-a2f13c0dc904.png)

2021-03-31 16:35 UTC, alkofahi commented on provision_environment/README.md
> +
Thanks for the feedback, I will create an issue to update the naming convention.

- Regarding the directory, the README is already in the directory, so I don't think that applies, right?
- Nice catch, I updated the README with instructions to log in and set a default account
- I updated the name creation for SA to remove any none alphanumeric chars. Not sure about retry, I think that is an added complexity that might be an overkill for the script. Let us chat more when you have time.

2021-03-31 16:43 UTC, gortegaMS commented on provision_environment/README.md
> +
About changing directory , it does apply since you can be reading the readme file from any location including directly from github, but in order to execute the commands you do need to actually be at the correct directory.

2021-03-31 18:08 UTC, merged