Reuse existing domain and consolidate monitoring documentation
retaildevcrews/caf-terraform-landingzones-starter pull request #25
Opened 2021-05-03 21:29 UTC by gortegaMS

### [Issue-732: Terraform scripts updated to reuse and deploy to an existing domain and dns zone](https://github.com/retaildevcrews/ngsa/issues/732)
### [Issue-758: Monitoring Traefik Ingress and PnP documentation consolidated ](https://github.com/retaildevcrews/ngsa/issues/758)
### [Issue-754: K8s version downgraded to v1.19.9 ](https://github.com/retaildevcrews/ngsa/issues/754)

## PR Checklist

---

- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [X] My code follows the code style of this project.
- [ ] I ran lint checks locally prior to submission.
- [X] Have you checked to ensure there aren't other open Pull Requests for the same update/change?

## Description

- Terraform scripts updated to reuse and deploy to an existing domain and dns zone
- Monitoring Traefik Ingress and PnP documentation consolidated 
- K8s version downgraded to v1.19.9

 

## Does this introduce a breaking change

- [ ] YES
- [X] NO

## Testing

Please follow instruction given in files "01-terraform.md" and "02-aks.md" from branch "gortegaMS-732"

2021-05-04 16:12 UTC, kev-ms requested changes

2021-05-04 16:12 UTC, kev-ms commented on enterprise_scale/construction_sets/aks/online/aks_secure_baseline/01-terraform.md
> +
NIT: extra lines between the instructions and the commands per rest of the repo

2021-05-04 16:12 UTC, kev-ms commented on enterprise_scale/construction_sets/aks/online/aks_secure_baseline/01-terraform.md
> +
Move this section `Terraform setup & environment deployment` after `Domain name and alias reord configuration
`? Currently deployment steps are pushed down but this section is still here

2021-05-04 16:12 UTC, kev-ms commented on enterprise_scale/construction_sets/aks/online/aks_secure_baseline/02-aks.md
>      # This website will be available at the public domain below
Remove this comment or list sample domain with application context root?
examples:
`https://<subdomain>.<domain>/memory`
` https://<subdomain>.<domain>/loderunner`

2021-05-04 16:12 UTC, kev-ms commented on enterprise_scale/construction_sets/aks/online/aks_secure_baseline/configuration/agw/agw_application.tfvars
> -        }
Probably comment this out and keep there for reference?

2021-05-04 16:12 UTC, kev-ms commented on enterprise_scale/construction_sets/aks/online/aks_secure_baseline/traefik/README.md
> +- Apply your app's yaml file
Missing associated command?

2021-05-05 13:12 UTC, gortegaMS commented on enterprise_scale/construction_sets/aks/online/aks_secure_baseline/01-terraform.md
> +
fixed

2021-05-05 13:13 UTC, gortegaMS commented on enterprise_scale/construction_sets/aks/online/aks_secure_baseline/01-terraform.md
> +
fixed

2021-05-05 13:16 UTC, gortegaMS commented on enterprise_scale/construction_sets/aks/online/aks_secure_baseline/02-aks.md
>      # This website will be available at the public domain below
fixed

2021-05-05 13:17 UTC, gortegaMS commented on enterprise_scale/construction_sets/aks/online/aks_secure_baseline/traefik/README.md
> +- Apply your app's yaml file
fixed

2021-05-05 13:24 UTC, gortegaMS commented on enterprise_scale/construction_sets/aks/online/aks_secure_baseline/configuration/agw/agw_application.tfvars
> -        }
I think it is not a good practice to leave code commented out that is not fully functionally, besides, if we want to keep it for reference, we have three sources to refer to 
github history , the original CAF project and azure caf project examples.

2021-05-05 17:01 UTC, kev-ms approved these changes
Looks good. Just need an adjustment on title for domain name per our conversation

2021-05-05 18:04 UTC, merged