Integrate provision env bash script with CAF
retaildevcrews/caf-terraform-landingzones-starter pull request #5
Opened 2021-04-06 00:11 UTC by Natasha-Kohli

# [Issue-id](https://github.com/retaildevcrews/ngsa/issues/630)

## PR Checklist

---

- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] My code follows the code style of this project.
- [ ] I ran lint checks locally prior to submission.
- [x] Have you checked to ensure there aren't other open Pull Requests for the same update/change?

## Description

Updated the script to add "Contributor" and "User Access Administrator" roles to the service principal. It's also setup to add Application.ReadWrite.All and Directory.ReadWrite.All as outlined in the [terraform documentation](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/guides/service_principal_configuration#method-2-api-access-with-admin-consent). This currently fails with an error because we don't use --admin-consent. This will be investigated in a future issue.
Documentation is updated so anyone can now run the provision env script and then terraform apply to deploy the CAF resources!

## Does this introduce a breaking change

- [ ] YES
- [x] NO

## Testing

2021-04-06 15:04 UTC, alkofahi requested changes

2021-04-06 15:04 UTC, alkofahi commented on enterprise_scale/construction_sets/aks/online/aks_secure_baseline/01-terraform.md
> +./provision-environment.sh -a myapp -t <your tenant name> -f
nit: myapp -> <your app name>

2021-04-06 15:04 UTC, alkofahi commented on enterprise_scale/construction_sets/aks/online/aks_secure_baseline/01-terraform.md
> +eval terraform apply ${parameter_files}
can this be added to the bash script? What are the pros/cons of doing that? 

It might be easier for us to also move the script folder to be with /enterprise_scale/construction_sets/aks, we can do that in a separate PR to avoid confusion

2021-04-06 15:04 UTC, alkofahi commented on enterprise_scale/construction_sets/aks/online/aks_secure_baseline/configuration/global_settings.tfvars
> +  random_length  = 0
I think Kevin has a draft PR to add this, if this is necessary for your PR to be functional, I would suggest aligning with him and have it as part of your PR

2021-04-06 15:04 UTC, alkofahi commented on provision_environment/_prepare-terraform.sh
> +  az role assignment create --assignee $servicePrincipalObjId --role "Contributor" --subscription $SUBSCRIPTION_ID
This gives the SP the ability to manage resources across the subscription, I think we should avoid that and only assign the needed permissions to manage the resources needed by the baseline infrastructure. Lines 163 & 164 in the old code show how.

2021-04-06 15:04 UTC, alkofahi commented on provision_environment/_prepare-terraform.sh
> +# Get MSGraphId
nit: spacing

2021-04-06 15:04 UTC, alkofahi commented on provision_environment/_prepare-terraform.sh
> +  az ad app permission add --id $servicePricipalId --api $graphId --api-permissions $dirReadAll=Scope $appReadWriteAll=Scope $appRoleDirReadAll=Role $appRoleAppReadWriteAll=Role
does the SP need all of these permissions? Can we restrict them to what the SP is managing?

2021-04-06 17:39 UTC, kev-ms commented on enterprise_scale/construction_sets/aks/variables.tf
> +variable "LOCATION" {
nit: could these variable be all lower case to be consistent with the rest of vars in file?

2021-04-06 19:58 UTC, Natasha-Kohli commented on enterprise_scale/construction_sets/aks/online/aks_secure_baseline/configuration/global_settings.tfvars
> +  random_length  = 0
Got it! Depending on who's PR merges first we can just pull the changes but for now I've made sure the PRs are consistent

2021-04-06 21:00 UTC, Natasha-Kohli commented on provision_environment/_prepare-terraform.sh
> +  az ad app permission add --id $servicePricipalId --api $graphId --api-permissions $dirReadAll=Scope $appReadWriteAll=Scope $appRoleDirReadAll=Role $appRoleAppReadWriteAll=Role
I've removed the delegated permissions since we'll only need the application permissions! Also added a comment that we might get rid of all the MSGraph permissions depending on our investigation in a future issue.

2021-04-06 21:13 UTC, Natasha-Kohli commented on enterprise_scale/construction_sets/aks/online/aks_secure_baseline/01-terraform.md
> +eval terraform apply ${parameter_files}
I think a pro to keeping them separate is if you're working on changes to the terraform file, you won't want to run the whole script and create a service principal every time, you'll just want to run terraform init and all the other commands until apply. However, if we are running the provision environment script to create the SP, chances are you'll also want to run the terraform commands.

I think the best solution is to probably create a new script that handles all the terraform commands. This can be called by itself for somebody working on the terraform files and can also be called within the provision env script.

2021-04-06 21:14 UTC, Natasha-Kohli commented on enterprise_scale/construction_sets/aks/online/aks_secure_baseline/01-terraform.md
> +./provision-environment.sh -a myapp -t <your tenant name> -f
Should I change "myapp" to something else? I copied this directly from the script's readme

2021-04-07 00:54 UTC, Natasha-Kohli commented on provision_environment/_prepare-terraform.sh
> +  az role assignment create --assignee $servicePrincipalObjId --role "Contributor" --subscription $SUBSCRIPTION_ID
Talked to Jafar - will discuss as a team during sprint planning if we want to pursue this!

2021-04-07 03:24 UTC, alkofahi commented on enterprise_scale/construction_sets/aks/online/aks_secure_baseline/01-terraform.md
> +./provision-environment.sh -a myapp -t <your tenant name> -f
lol wait, I think something went wrong it is supposed to be -> \<your app name\> but I didn't escape the \<\> 🤦

2021-04-07 03:31 UTC, alkofahi commented on enterprise_scale/construction_sets/aks/online/aks_secure_baseline/01-terraform.md
> +eval terraform apply ${parameter_files}
ok wait, the SP and Remote state resources are ONLY created if the -f flag is passed, so the SP + state won't be created every time. 

This script already has TF init and validate, given that the whole point is to set up TF for the first time (if needed), I think it would make sense to add the script here too. But, I am game if we want to refactor the script into something different

2021-04-07 20:24 UTC, Natasha-Kohli commented on enterprise_scale/construction_sets/aks/online/aks_secure_baseline/01-terraform.md
> +eval terraform apply ${parameter_files}
That's a good point, I think it can be integrated directly into the script then! I'll make a small PR after this one goes in to move the files around to their appropriate directories, which will affect these commands, so I'll include this change then.

2021-04-07 20:29 UTC, alkofahi approved these changes

2021-04-07 20:30 UTC, merged